### ISSUE TITLE
Opening a menu while another one is open -> Two context menus

### ISSUE THREAD

**Issue by Haz901** [Fabriquartz/ember-right-click-menu#19]

**Comment by eg271** [comment]
Any update on this issue?

**Comment by Haz901** [comment]
Thanks for bumping this. We have not yet resolved this issue, but we'll look into it shortly.

**Comment by Haz901** [comment]
It appears that this problem was never actually caused by the addon, but rather by something in our application calling `stopPropagation` on the `contextmenu` event. I mistakenly thought this to be a problem in the addon.

I'm closing this issue for now, but feel free to open a new one if this problem still occurs for you and can help us reproduce it.
