### ISSUE TITLE
Embroider-enabled app breaks functionality

### ISSUE THREAD

**Issue by Alexander-Krause-Glau** [Fabriquartz/ember-right-click-menu#30]
I have a Embroider-enabled app that uses this addon and `"@popperjs/core": "^2.11.6"` as dependency. Upon right click I get the following error message:

![grafik](https://user-images.githubusercontent.com/9912468/188882642-296c1cd0-9ce3-490c-bf34-d6b7b37bb9be.png)

Downgrading to `"@popperjs/core": "^2.9.2"` does not fix the problem. The problem does not occur when I disable Embroider and use the classic build process.

**Comment by michaelw8** [comment]
solved by #40
