### ISSUE TITLE
Error on Click "Uncaught TypeError: e.path is undefined"

### ISSUE THREAD

**Issue by ank97** [Fabriquartz/ember-right-click-menu#34]
I noticed this console error on my local setup as well as on the demo website here: https://fabriquartz.github.io/ember-right-click-menu/

**Comment by Haz901** [comment]
Thanks for reporting! I don't seem to get the error myself at this moment. Could you tell me what browser & OS you are using when you get this?

**Comment by ank97** [comment]
Hi! I saw this using Firefox 104.0 (64-bit) (Mozilla Firefox for Ubuntu
canonical - 1.0) - on Linux (Ubuntu 20.04.5 LTS).

**Comment by Haz901** [comment]
Okay, it seems like this error only occurs on Firefox. I'll look into it
